name = "CoordinateBisection"
uuid = "fbbb2451-6dde-4807-9c10-ea24ace8c95b"
authors = ["Andrei-Leonard Nicusan <a.l.nicusan@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
StaticArrays = "1.5"
julia = "1.0"
